name: grow_habit
description: "A clean and modern habit tracking application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Firebase + Auth
  firebase_core: ^3.7.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # Firebase utils (Firebase Auth & Firestore)
  firebase_auth_platform_interface: ^7.1.4
  cloud_firestore_platform_interface: ^6.3.4

  # Local Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # Others
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add your images/icons later here
    - assets/images/
    - assets/icons/
